services:
    db:
        image: postgres:latest
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        ports:
            - '5432:5432'
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - stdiscm-network

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
        depends_on:
            - db
        networks:
            - stdiscm-network

    discovery-server:
        build: ./discovery-server
        container_name: discovery-server
        ports:
            - '8761:8761'
        networks:
            - stdiscm-network
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    api-gateway:
        build: ./api-gateway
        container_name: api-gateway
        ports:
            - '8081:8081'
        depends_on:
            - discovery-server
        networks:
            - stdiscm-network
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
            - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
            - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWERCASE_SERVICE_ID=true

    auth-service:
        build: ./auth-service
        container_name: auth-service
        ports:
            - '8082:8082'
        depends_on:
            - discovery-server
        networks:
            - stdiscm-network
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
            - SPRING_APPLICATION_NAME=auth-service

    # frontend-service:
    #     build: ./frontend-service
    #     container_name: frontend-service
    #     ports:
    #         - '8080:8080'
    #     depends_on:
    #         - discovery-server
    #         - auth-service
    #     networks:
    #         - stdiscm-network
    #     environment:
    #         - SPRING_PROFILES_ACTIVE=docker
    #         - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    #         - AUTH_SERVICE_URL=http://auth-service:8081
    #         - SPRING_APPLICATION_NAME=frontend-service

    course-service:
        build: ./course-service
        container_name: course-service
        ports:
            - '8083:8083'
        depends_on:
            - discovery-server
        networks:
            - stdiscm-network
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
            - SPRING_APPLICATION_NAME=course-service

    enrollment-service:
        build: ./enrollment-service
        container_name: enrollment-service
        ports:
            - '8084:8084'
        depends_on:
            - discovery-server
            - course-service
        networks:
            - stdiscm-network
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
            - SPRING_APPLICATION_NAME=enrollment-service

    grade-service:
        build: ./grade-service
        container_name: grade-service
        ports:
            - '8085:8085'
        depends_on:
            - discovery-server
            - enrollment-service
        networks:
            - stdiscm-network
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
            - SPRING_APPLICATION_NAME=grade-service

    notification-service:
        build: ./notification-service
        container_name: notification-service
        ports:
            - '8086:8086'
        depends_on:
            - discovery-server
            - enrollment-service
        networks:
            - stdiscm-network
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
            - SPRING_APPLICATION_NAME=notification-service

volumes:
    db_data:
        name: stdiscm_db_data

networks:
    stdiscm-network:
        driver: bridge
