spring:
  application:
    name: api-gateway
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        # Route for Auth Service
        - id: auth-service
          uri: http://localhost:8081  # Direct URL for local development
          predicates:
            - Path=/auth/**  # Route requests starting with /auth/** to the Auth Service

        # Route for Frontend Service
        - id: frontend-service
          uri: http://localhost:8082  # Direct URL for local development
          predicates:
            - Path=/login/**  # Route requests starting with /login/** to the Frontend Service
            - Path=/home/**   # Route requests starting with /home/** to the Frontend Service
            - Path=/courses/** # Route requests for courses (or other frontend views) to Frontend Service

        - id: course-service
          uri: http://localhost:8083  # Direct URL for local development
          predicates:
            - Path=/courses/**  # Forward requests starting with /courses/** to Course Service

        # Enrollment Service Routes
        - id: enrollment-service-all
          uri: http://localhost:8084
          predicates:
            - Path=/enrollment
            - Method=GET
          filters:
            - RewritePath=/enrollment, /enrollment

        - id: enrollment-service-enroll
          uri: http://localhost:8084
          predicates:
            - Path=/enrollment
            - Method=POST
          filters:
            - RewritePath=/enrollment, /enrollment

        - id: enrollment-service-cancel
          uri: http://localhost:8084
          predicates:
            - Path=/enrollment/{id}
            - Method=DELETE
          filters:
            - RewritePath=/enrollment/(?<id>.*), /enrollment/$\{id}

        # Grade Service Routes
        - id: grade-service-all
          uri: http://localhost:8085
          predicates:
            - Path=/grades
            - Method=GET
          filters:
            - RewritePath=/grades, /grades

        - id: grade-service-by-student-course
          uri: http://localhost:8085
          predicates:
            - Path=/grades/student/{studentId}/course/{courseId}
            - Method=GET
          filters:
            - RewritePath=/grades/student/(?<studentId>.*)/course/(?<courseId>.*), /grades/student/$\{studentId}/course/$\{courseId}

        - id: grade-service-assign
          uri: http://localhost:8085
          predicates:
            - Path=/grades
            - Method=POST
          filters:
            - RewritePath=/grades, /grades

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL of the Eureka Server
    register-with-eureka: false
    fetch-registry: false
    enabled: false  # Disable Eureka client completely for local development

server:
  port: 8080