spring:
  application:
    name: frontend-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka Server URL

server:
  port: 8082  # Port for Frontend Service